version: '3.8'

services:
  watcher:
    ports:
      - '8081:80'

  postgres:
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=web@watcher.ru
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '9090:80'
    networks:
      - internal
